name: Build 

on:
  pull_request: 
        types: [ opened, edited, synchronize, reopened ] 

jobs:
  GithubTest:
    name: TiCS
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: TICS Action Run
        uses: tiobe/tics-github-action@v3
        with:
          project: 'cpp-game-git'
          branchname: 'main'
          ticsAuthToken: ${{secrets.TESTLAB_VIEWER}}
          viewerUrl: 'https://testlab.tiobe.com/tiobeweb/testlab/api/cfg?name=default'
          calc: 'CS'
          installTics: true
          
    
